apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skillpulse-stg
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/dikshitbonu-bit/github-actions-kubernetes-masterclass
    targetRevision: feat/hackathon-improvements
    path: helm/skillpulse
    helm:
      valueFiles:
        - values.yaml
        - values-stg.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: skillpulse-stg
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
